export const PAKISTAN_CITIES = [
    "18 HAZARI",
    "ABBASPUR (a.k)",
    "ABBOTABAD",
    "ABDUL HAKIM",
    "ADDA BUN BOSAN",
    "ADDA LAR",
    "ADDA ZAKHEERA",
    "ADYALA ROAD",
    "AHMED PUR EAST",
    "AHMED PUR LAMMA",
    "AHMED PUR SIAL",
    "AL PURI",
    "ALI PUR CHATTA",
    "ALIPUR",
    "AMINPUR BANGLOW",
    "ARIF WALA",
    "ASTORE",
    "ATTOCK",
    "AWARAN",
    "BADIN",
    "BAGH",
    "Bagh (a.k.)",
    "BAHAWALNAGAR",
    "BAHAWALPUR",
    "BAJUR",
    "BAJWAR",
    "BAKRA MANDI",
    "BALAKOT",
    "BANGLOW GOGERA",
    "BANNU",
    "BARA KAHU",
    "Bari kot",
    "Barikot",
    "BARKHAN",
    "BARNALA",
    "BASIR PUR",
    "BASTI MALOOK",
    "batgram",
    "BATKHELA",
    "BATTGRAM",
    "beesham",
    "BELA",
    "BEWAL",
    "BHAI PHARU",
    "BHAKKAR",
    "BHALWAL",
    "BHAWANA",
    "BHERA",
    "BHIMBER",
    "BHIRIA",
    "BHIRIA CITY",
    "BHIRIA ROAD",
    "BHIT SHAH",
    "BHITSHAH",
    "bhone",
    "BISHAM",
    "Bloouch (a.k.)",
    "BOONI",
    "BUCHEKI",
    "BUCHIANA MANDI",
    "BUDHLA SANT",
    "BULRI SHAH KARIM",
    "BUNAIR",
    "BUREWALA",
    "CENTAURUS MALL",
    "CHACHRO",
    "Chak beli khan",
    "CHAK JHUMRA",
    "CHAK SAWARI",
    "CHAKDARA",
    "CHAKWAL",
    "CHAMAN",
    "CHARSADDA",
    "CHASHMA",
    "CHAWINDA",
    "CHENAB NAGAR",
    "CHICHAWATNI",
    "CHINAR",
    "CHINIOT",
    "CHISHTIAN",
    "CHITRAL",
    "CHOA SYDEN SHAH",
    "CHOHAR JAMALI",
    "CHOR CANTT",
    "CHORE",
    "CHOTI",
    "CHOWK AZAM",
    "CHOWK SARWER SHAHEED",
    "CHUNIA",
    "CHUNIAN",
    "cotla",
    "DADU",
    "DADYAL (A.K)",
    "DAHARKI",
    "DAHRANWALA",
    "Daira Din Panna",
    "DAKOTA",
    "DALBANDIN",
    "DARA ADM KHEL",
    "DARBELLO",
    "DARGAI",
    "DAROSH",
    "DARY KHAN",
    "DARYA KHAN",
    "DASKA",
    "DAUD KHEL",
    "Daul Tala",
    "DAULAT NAGAR",
    "DAULATPUR",
    "DAUR",
    "DEPAL PUR",
    "Depalpur",
    "DERA ALLAHYAR",
    "DERA BUGTI",
    "DERA GHAZI KHAN",
    "DERA ISMAIL KHAN",
    "DERAMURAD JAMAL",
    "DHABEJI",
    "DHANOT",
    "DHARANWALA",
    "DHEERKOT",
    "DHODHAK",
    "DHUDIAL",
    "DIGRI",
    "DIJKOT",
    "DINA",
    "DINGA",
    "DOKRI",
    "DOMAIL",
    "DONGI (A.K)",
    "DOUR",
    "DUKKI",
    "DULLE WALA",
    "DUNYA PUR",
    "ELLAH ABAD",
    "ESA KHEL",
    "essakhail",
    "FAISALABAD",
    "FARROQABAD",
    "FATEH JANG",
    "FATEHPUR",
    "FAZIL PUR",
    "FEROZ WATOWAN",
    "FEROZA",
    "FORTE ABBAS",
    "G-10 MARKAZ",
    "GADOON AMAZAI",
    "GAGGO MANDI",
    "GAHKUCH GHIZER",
    "GAMBAT",
    "GARH MOR",
    "GARHI YASIN",
    "GARI HABIBULLAH",
    "GARI KHAIRO",
    "GAWADAR",
    "GHAKAR",
    "GHARO",
    "GHAZI ABAD",
    "GHOTKI",
    "GHOUS PUR",
    "GILGIT",
    "GOJRA",
    "GOLARCHI",
    "GOLRA MORE",
    "GOTH MACHI",
    "GUDDU",
    "GujarKhan",
    "GUJRANWALA",
    "GUJRAT",
    "HAFIZABAD",
    "HAJIRA",
    "HALA",
    "Halani",
    "HANGU",
    "HARIPUR",
    "HARNAI",
    "HARNOULI",
    "HAROONABAD",
    "HARRAPA",
    "HASILPUR",
    "HASSAN ABDAL",
    "HATTER",
    "HAVELI LAKHA",
    "HAVELLIAN",
    "HAZRO",
    "HEAD RAJKAN",
    "HUB",
    "HUB CHOKI",
    "HUJRA SHAMUQEEM",
    "HUMAK",
    "HUNZA",
    "HYDERABAD",
    "IKHLAS",
    "IQBAL NAGAR",
    "ISKANDARABAD",
    "ISLAM GARH",
    "ISLAMABAD",
    "ISLAMKOT",
    "ISSA KHEL",
    "JACOBABAD",
    "JAFRABAD",
    "JAHANIAN",
    "JALAL PUR",
    "JALAL PUR BHATTIAN",
    "JALALPUR JATTAN",
    "JALALPUR PEERWALA",
    "JALALPUR SHARIF",
    "JALALPURPIRWALA",
    "JAMALDIN WALI",
    "JAMPUR",
    "JAMSHORO",
    "JAND",
    "JAND WALA",
    "JARANWALA",
    "JARWAR",
    "JATOI",
    "JAWARIAN",
    "JHAMPIR",
    "JHANG",
    "JHANGIRA",
    "JHANIAN",
    "JHAT PAT",
    "JHELUM",
    "JHOL",
    "JHUDDO",
    "JOUHARABAD",
    "KABAL",
    "KABIR WALA",
    "KACHA KHO",
    "KAHOTA",
    "KALA BAGH",
    "KALA SHAH KAKU",
    "KALAR KAHAR",
    "KALAR SYEDAN",
    "KALASKEY",
    "KALAT",
    "Kallar Saydian",
    "KALOOR KOT",
    "KAMALIA",
    "KAMBAR ALI KHAN",
    "KAMER MOSHANI",
    "KAMOKE",
    "KAMRA",
    "KANA NAU",
    "KANDH KOT",
    "KANDIARI",
    "KANDYARO",
    "KANGANPUR",
    "KARACHI",
    "KARAK",
    "KARIO GHANWAR",
    "KAROR LALESAN",
    "KAROR PAKKA",
    "KASHMORE",
    "KASOWAL",
    "KASUR",
    "KATLANG",
    "KHAIPUR TAMEWAL",
    "KHAIR PUR TAMIANWALI",
    "KHAIRPUR",
    "khairpur mirs",
    "KHAIRPUR NATHAN",
    "KHAN BELA",
    "khan Gah Dogran",
    "KHANEWAL",
    "KHANGARH",
    "KHANPUR",
    "KHANQA DOGRAN",
    "KHANQA SHARIF",
    "KHAPLU",
    "KHARAN",
    "KHARIAN",
    "KHARIAN CANTT",
    "KHAWAZA KHELLA",
    "KHAZAKHELA",
    "KHEWRA",
    "KHEWRA DANDOT",
    "KHIAR PUR TAMEWALI",
    "KHIDDER WALA",
    "KHIPRO",
    "KHORE",
    "KHOSKI",
    "Khuratta (a.k)",
    "KHURIANWALA",
    "KHUSHAB",
    "KHUZDAR",
    "KOHAT",
    "kohlu",
    "KOT ABDUL MALIK",
    "KOT ADDU",
    "KOT CHUTTA",
    "KOT DEJI",
    "KOT GHULAM MUHD",
    "KOT JAMEL",
    "KOT MITTHAN",
    "KOT MOMIN",
    "KOT RADHA KISHA",
    "KOT SAMABAH",
    "KOTLA ARBAB ALI KHAN",
    "KOTLI AZAD KASHMIR",
    "KOTLI-A.KASHMIR",
    "KOTRI",
    "KUCHLAK",
    "KUNDIAN",
    "KUNJAH",
    "KUNRI",
    "KUSHAB",
    "LAHORE",
    "LAKI MARWAT",
    "LALAMUSA",
    "LALIAN",
    "LANDIKOTAL",
    "LARKANA",
    "lasbela",
    "LAYYAH",
    "LIAQUATPUR",
    "LODHRAN",
    "LORA LAI",
    "Lower DIR",
    "MACHI GOTH",
    "MADYAN",
    "Mailsi",
    "MAKHDOOM AALI",
    "MAKHDOOM PUR",
    "makhdoom rasheed",
    "MALAK WAL",
    "MALAKAND",
    "MALSI",
    "MAMUN KANJAN",
    "MANAWALA",
    "MANDI BAHAUDDIN",
    "MANDI FAIZ ABAD",
    "mandi sadiq gunj",
    "MANGA MANDI",
    "MANGLA",
    "MANGOWAL",
    "MANKERA",
    "MANSHERA",
    "MARDAN",
    "MASTUNG",
    "MATIARI",
    "MATLI",
    "MATTA (SWAT)",
    "matta swat",
    "MEHAR",
    "MEHMOODKOT",
    "MEHRAB PUR",
    "MIAN CHANOO",
    "Miani",
    "MIANWALI",
    "MINCHANABAD",
    "MINGORA",
    "MINGORA (SWAT)",
    "MIRAN SHAH",
    "MIRPUR A.K.",
    "MIRPUR KHAS",
    "MIRPUR MATHELO",
    "MIRPUR SAKRO",
    "MIRWAH GORCHANI",
    "MITHI",
    "MITYARI",
    "MOR KUNDA",
    "MORO",
    "MUBARAK PUR",
    "MUCH",
    "MUHAMMAD PUR DEEWAN",
    "MULTAN",
    "munda",
    "MURID WALA",
    "MURIDKEY",
    "MURREE",
    "MUSLIM BAGH",
    "MUZAFFARABAD AK",
    "MUZAFFARGARH",
    "NAKYAL",
    "NANKANA SAHIB",
    "narang mand",
    "NAROWAL",
    "NARWALA BANGLA",
    "NASIRABAD",
    "NAUABAD",
    "NAUDERO",
    "Naukot",
    "NAUSHERA",
    "NAWABSHAH",
    "NEW JATOI",
    "NEW SAEEDABAD",
    "NOORIABAD",
    "NOORPUR",
    "NOSHERO FEROZ",
    "NOSHKI",
    "NOUKOT",
    "NOWSHERA",
    "NOWSHERA VIRKA",
    "NURPUR THAL",
    "OGHI",
    "OKARA",
    "OKARA CANTT",
    "OLE KHI",
    "OLE LHE",
    "OLE RWP",
    "ORMARA",
    "PABBI",
    "PACCA CHANG",
    "PAHAR PUR",
    "Pahrianwali",
    "PAINSRA",
    "PAK PATTAN SHARIF",
    "PALANDRI",
    "PANJGOOR",
    "PANJGOR",
    "PANNU AKIL",
    "PANU AQIL CANTT",
    "PARA CHINAR",
    "PASNI",
    "PASROOR",
    "PASRUR",
    "PATOKI",
    "PATTOKI",
    "PESHAWAR",
    "PETARO",
    "PHALIA",
    "PHULLARWAN",
    "PIND DADAN KHAN",
    "PINDI BHATIAN",
    "PINDI GHEB",
    "PIPLAN",
    "pir jo goth",
    "PIR MAHAL",
    "PIRYALO",
    "PISHIN",
    "POTHA (A.K)",
    "PULANDRI",
    "QABOOLA",
    "QADIRPUR RAWAN",
    "QALANDRABAD",
    "QAZI AHMED",
    "QILA DEDAR SING",
    "qila kallarwala",
    "QILLA SAIFULLAH",
    "QUAIDABAD",
    "QUETTA",
    "Rabwa",
    "RABWAH",
    "RADHAN",
    "RADHAN STATION",
    "RAHIMYARKHAN",
    "RAHWALI",
    "RAIWAND",
    "RAJANA",
    "RAJANPUR",
    "RAKHNI",
    "RANIPUR",
    "RATTO DERO",
    "RAWALAKOT",
    "Rawalakot (a.k)",
    "RAWALPINDI",
    "RAWAT",
    "REHMANI NAGAR",
    "RENALA KHURD",
    "RISALPUR",
    "RIWAND",
    "ROHILANWALI",
    "ROHRI",
    "RUSTAM",
    "SADIQABAD",
    "SAFDARABAD",
    "SAHIWAL",
    "SAHIWAL - FSD",
    "SAIDU SHARIF",
    "SAKARDU",
    "SAKRAND",
    "SAMANDRI",
    "SAMARO",
    "SAMBRIAL",
    "SANAWAN",
    "SANDHILIAN WALI",
    "SANGHAR",
    "SANGLA HILL",
    "SARGODAH",
    "SARWAR SHAHEED",
    "SATIANA BANGLA",
    "Sehnsa (a.k.)",
    "SEHWAN",
    "SENSA",
    "SERAI NAURANG",
    "SHABQADAR",
    "SHADI LARGE",
    "SHAHAPUR CHAKAR",
    "SHAHDAD KOT",
    "SHAHDADKOT",
    "SHAHDADPUR",
    "SHAHDARA",
    "SHAHER SULTAN",
    "SHAHKOT",
    "SHAHPUR",
    "SHAKAR GARH",
    "shangla",
    "SHARAQPUR",
    "Shawa Adda",
    "SHEIKHUPURA",
    "SHIKARPUR",
    "SHINKIARI",
    "SHORKOT",
    "SHUJAABAD",
    "SIALKOT",
    "Sibbi",
    "SIBI",
    "SILANWALI",
    "SINJHORO",
    "SITA ROAD",
    "SKARDU",
    "Sobho Dero",
    "Sohawa",
    "SOHBATPUR",
    "SRAI ALAMGEER",
    "SUI",
    "SUJAWAL",
    "SUKKUR",
    "SUMANDARI",
    "SUMBRIAL",
    "SUNDAR ADDA",
    "SWABI",
    "SWAT",
    "TAKHAT BAI",
    "TALAGANG",
    "TALL",
    "TANDA",
    "TANDLIANWALA",
    "TANDO ADAM",
    "TANDO ALLAYAR",
    "TANDO BAGHO",
    "Tando ghulam al",
    "Tando Ghulam Ali",
    "TANDO JAM",
    "TANDO JAN MOHD",
    "TANDO MOHD KHAN",
    "TANGI",
    "TANK",
    "Taranda Muhammad panah",
    "tarbela",
    "TAUNSA SHARIF",
    "TAXILA",
    "TAXLA",
    "TEHKAL",
    "TEMARGARAH",
    "TERNOL",
    "THALL",
    "THARO SHAH",
    "Tharparkar",
    "THARRI MIR WAH",
    "THATTA",
    "THULL",
    "TIBBA SULTAN",
    "TKHAT BHAI",
    "Toba Tek Sing",
    "TOPI",
    "TRARKHEL",
    "turbat",
    "UBARO",
    "UCH SHARIF",
    "UMERKOT",
    "UPPER DIR",
    "USTA MHMD",
    "UTHAL",
    "VARI DIR",
    "VEHARI",
    "WAH",
    "WAH CANTT",
    "WAN BACHRAN",
    "WANA",
    "WARAH",
    "WARI DIR",
    "WAZ",
    "WAZEERABAD",
    "WAZIRABAD",
    "winder",
    "YAZMAN",
    "YAZMAN MANDI",
    "ZAFARWAL",
    "ZAHIRPEER",
    "zhob",
    "ZIARAT"
];